project:
  type: default
  execute-dir: file
  render:
    - {{< var patient >}}.qmd

format:
  neurotyp-typst:
    keep-typ: true
    keep-md: true
    papersize: "us-letter"
    bodyfont: "ScholaX"
    sansfont: "Work Sans" #"ScholaX"
    fontsize: 12pt
    number-sections: false
    citeproc: false
    csl: /src/bib/apa

execute:
  warning: false
  echo: false
  message: false
  freeze: auto
  cache: true

editor:
  markdown:
    wrap: sentence
    canonical: true
fig-width: 6
fig-asp: 0.618
out-width: 70%
fig-align: center
fig-format: svg
fig-dpi: 270
df-print: kable
reference-location: document
bibliography: /src/bib/refs.bib
